name: Dummy POC for locally hosted github runners

on:
  workflow_dispatch:

jobs:
  work:
    runs-on: ubuntu-slim
    timeout-minutes: 1
      
    steps:
      - name: Print hello world 
        run: echo "hello world"
